#ifndef FONTFILES_H_
#define FONTFILES_H_

static char *fonts[] = {
		"aerof-Aero Fighters (Kaneko).png",
		"aftb-Afterburner (Sega).png",
		"aof2-Art of Fighting 2 (SNK).png",
		"arab-Arabian Magic (Capcom).png",
		"arka-ArkArea (UPL).png",
		"armo-ArmoredWarriors (Capcom).png",
		"ass-Assault (Namco).png",
		"astx-Asterix (Konami).png",
		"atascii-ATASCII.png",
		"aura-Aurail (Sega).png",
		"avng-Avengers (Capcom).png",
		"bakr-Battle Bakraid (Eighting).png",
		"bats-Batsugun (Toaplan).png",
		"bcir-BattleCircuit (Capcom).png",
		"bdash-Boulder Dash (Data East).png",
		"bios-BioShipPaladin (UPL).png",
		"blaz-Blazing Star (Yumekobo).png",
		"blkt-Black Tiger (Capcom).png",
		"blwa-Blood Warrior (Kaneko).png",
		"bonz-Bonanza Bros (Sega).png",
		"boog-Boogie Wings (Data East).png",
		"bubs-Bubble Symphony (Taito).png",
		"caml-Cameltry (Taito).png",
		"chiki-Chiki Chiki Boys (Capcom).png",
		"cliff-Cliffhanger - Edward Randy (DataEast).png",
		"cmnds-Commando-Special (Capcom).png",
		"cotn-Cotton (Sega + Success).png",
		"cshk-Captain Sky Hawk (RARE).png",
		"cyba-Cybattler (Jaleco).png",
		"dddon-Don Doko Don (Taito).png",
		"ddp-DoDonPachi (Cave).png",
		"DDR-Dance Dance Revolution (Konami).png",
		"ddux-Dynamite Dux (Sega).png",
		"dima-Dimahoo (Raizing).png",
		"drbr-Dragon Breed (Irem).png",
		"dsab-Dragon Saber (Namco).png",
		"dspir-Dragon Spirit (Namco).png",
		"flak-Flak Attack (Konami).png",
		"flys-Flying Shark (Taito).png",
		"fstarf-Final Star Force (Tecmo).png",
		"fz-Fantasy Zone (Sega).png",
		"gaia-Gaiapolis (Konami).png",
		"gain-Gain Ground (Sega).png",
		"garou-Garou Densetsu (SNK).png",
		"gng1-Ghosts n Goblins (Capcom).png",
		"gng2-Ghouls n Ghosts (Capcom).png",
		"gond-Gondomania (Data East).png",
		"gradius2-Gradius 2 (Konami).png",
		"gradius3-Gradius 3 (Konami).png",
		"gradius4-Gradius 4 (Konami).png",
		"gradius-Gradius.png",
		"guar-Guardians (Banpresto).png",
		"gunb-GunBuster (Taito).png",
		"gunn-GunNail (NMK).png",
		"guns-Gun.Smoke (Capcom).png",
		"gyrs-Gyruss (Konami).png",
		"hach-Hacha Mecha Fighter (NMK).png",
		"hatt-Hat Trick Hero 95 (Taito).png",
		"imgf-Image Fight (IREM).png",
		"kais-Kaiser Knuckle (Taito).png",
		"KETSUI-Ketsui (Cave).png",
		"kiki-Kiki Kaikai (Taito).png",
		"kira-Kirameki Star Road (Taito).png",
		"klaxa-Klax Alternate (Atari).png",
		"klax-Klax (Atari).png",
		"KoF2k1-King of Fighters 2001 (SNK).png",
		"KoF2k2-King of Fighters 2002 (SNK).png",
		"KoF2k3-King of Fighters 2003 (SNK).png",
		"KoF2k-King of Fighters 2000 (SNK).png",
		"kof97i-King of Fighters 97 Italic (SNK).png",
		"kof97-King of Fighters 97 (SNK).png",
		"ladu-Last Duel (Capcom).png",
		"lastb-Last Blade 2 (SNK).png",
		"last-Last Resort (SNK).png",
		"libr-Light Bringer (Capcom).png",
		"lwing-Legendary Wings (Capcom).png",
		"mars-Mars Matrix (Capcom).png",
		"moma-Monster Mauler (Konami).png",
		"mt-Major Title (IREM).png",
		"muni-Mutant Night (UPL).png",
		"mwar-Metal Warriors (Konami).png",
		"namco2-Namco Classic Gradient.png",
		"namco-Namco Classic.png",
		"nds-Dangerous Seed (Namco).png",
		"nebu-Nebulas Ray (Namco).png",
		"niga-Ninja Gaiden (Tecmo).png",
		"ninjas-Ninja Spirit (IREM).png",
		"ninj-Ninja Masters (ADK).png",
		"outf-Outfoxies (Namco).png",
		"pabom-Panic Bomber (Hudson).png",
		"pckf-Pickford Brothers.png",
		"psr2-Pachinko Sexy Reaction 2 (Sammy).png",
		"pubu-Puzzle Bobble (Taito).png",
		"puls-Pulstar (Aicom).png",
		"quake-Quake (id).png",
		"raph-Rapid Hero (MTC).png",
		"rayf-RayForce (Taito).png",
		"rf-Raiden Fighters (Seibu).png",
		"robot-Robotron (Williams).png",
		"rtl-R Type LEO (Irem).png",
		"rtype-R Type (Irem).png",
		"rumba-Rumba Lumber (Taito).png",
		"sala2-Salamander 2 (Konami).png",
		"samsho2-Samurai Shodown 2 (SNK).png",
		"samsho3-Samurai Shodown 3 (SNK).png",
		"sdi-SDI (Sega).png",
		"sexy-Parodius (Konami).png",
		"sf2-Street Fighter II (Capcom).png",
		"sfz3-Street Fighter Zero 3 (Capcom).png",
		"shda-ShadowDancer (Sega).png",
		"shinobi-Shinobi (Sega).png",
		"simp-The Simpsons (Konami).png",
		"skys-Sky Soldier (SNK).png",
		"smar-Super Mario Bros 3 (Nintendo).png",
		"snow-Snow Bros (Toaplan).png",
		"sold-Soldam (Data East).png",
		"solo-Solomons Key (Tecmo).png",
		"spdr-Speed Rumbler (Capcom).png",
		"ssf2-Super Street Fighter 2 (Capcom).png",
		"taitoa-Bubble Memories Alien (Taito).png",
		"terra-Terra Force (Nichibutsu).png",
		"tetris-Tetris (Sega).png",
		"thdr-Thunder Dragon (NMK).png",
		"times-Time Soldiers (ADK).png",
		"tp84-Time Pilot 84 (Konami).png",
		"trs-Top Ranking Stars (Taito).png",
		"trx-Truxton (Toaplan).png",
		"twin2-Twin Cobra II (Taito).png",
		"twin-Twin Cobra (Toaplan).png",
		"twq-Twin Qix (Taito).png",
		"typh-Typhoon (Konami).png",
		"unsq-UN Squadron (Capcom).png",
		"vict-Victory Road (SNK).png",
		"waku-Waku Waku 7 (Sunsoft).png",
		"wboy-Wonder Boy (Sega).png",
		"will-Willow (Capcom).png",
		"xexex-Xexex (Konami).png"
};

#endif /* FONTFILES_H_ */
